EU_dataset_nm: '이동의자유맵_배리어데이터_20220101-20221026.csv'
sk_dataset_nm: 'SK유동인구\시간대\부산광역시_FLOW_TIME_201801.CSV'
SAVE_PATH: '2022-08-17'
Weight:
  '안내시설': -1
  '경사': 3
  '통행폭': 4
  '높이': 2
  '돌출물': 3
  '단차': 4
  '마감': 1


